### ISSUE TITLE
Type Error while generating interceptors

### ISSUE THREAD

**Issue by m-schreiber** [magesuite/frontend#1] opened 2019-06-07 08:05 UTC
**Description**
* Magento: 2.3
* magento/module-catalog: 103.0.1
* PHP: 7.2
* creativestyle/magesuite-frontend: 2.1.8

Getting a Fatal Error during `setup:di:compile` with php7.2 (with php7.1 everything is fine):

`PHP Fatal error:  Declaration of MageSuite\Frontend\Model\Indexer\Category\Product\Action\Full\Interceptor::execute(): MageSuite\Frontend\Model\Indexer\Category\Product\Action\Full must be compatible with Magento\Catalog\Model\Indexer\Category\Product\Action\Full::execute(): Magento\Catalog\Model\Indexer\Category\Product\Action\Full in /var/www/project-haus-garten24/generated/code/MageSuite/Frontend/Model/Indexer/Category/Product/Action/Full/Interceptor.php on line 7`

This is not necessarily a Issue with this Module but an undocumented breaking change in php7.2
(see https://bugs.php.net/bug.php?id=75590).
Or
With the way Magento has implemented their involved class.

But

You could fix it by removing the preference from this module, since it does not do anything anymore with `magento/module-catalog:103.0.1`, as far as i can tell by a quick look.

**Steps to reproduce**
* Install Magesuite in Magento2.3 running on php7.2
* Compile Interceptors (setup:di:compile)

**Expected behavior**
`setup:di:compile` finishes without error.

**Suggested Solution**
Remove preference in this module (see description).

**Comment by diwipl** [comment] 2019-06-07 08:07
Thank you for your report. 

I will close this one since it's a duplicate of https://github.com/magesuite/magesuite/issues/5 and we're already working on it.

**Closed as completed by diwipl** 2019-06-07 08:07 UTC
